find_package(PkgConfig)
pkg_check_modules(PC_ROSCO QUIET ROSCO)

#find_path(ROSCO_INCLUDE_DIR
#  NAMES foo.h
#  PATHS ${PC_ROSCO_INCLUDE_DIRS}
#  PATH_SUFFIXES Foo
#)

find_library(ROSCO_LIBRARY
  NAMES discon
  PATHS ${PC_ROSCO_LIBRARY_DIRS}
)

#find_library(ROSCO_LIBRARY_RELEASE
#  NAMES discon
#  PATHS ${PC_ROSCO_LIBRARY_DIRS}/Release
#)
#find_library(ROSCO_LIBRARY_DEBUG
#  NAMES discon
#  PATHS ${PC_ROSCO_LIBRARY_DIRS}/Debug
#)

#include(SelectLibraryConfigurations)
#select_library_configurations(ROSCO)

set(Foo_VERSION "2.5.1") #${PC_ROSCO_VERSION})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(ROSCO
  FOUND_VAR ROSCO_FOUND
  REQUIRED_VARS
    ROSCO_LIBRARY
    #ROSCO_INCLUDE_DIR
  VERSION_VAR ROSCO_VERSION
)

if(ROSCO_FOUND)
  set(ROSCO_LIBRARIES ${ROSCO_LIBRARY} ${CMAKE_DL_LIBS})
  #set(ROSCO_INCLUDE_DIRS ${ROSCO_INCLUDE_DIR})
  set(ROSCO_DEFINITIONS ${PC_ROSCO_CFLAGS_OTHER})
endif()

if(ROSCO_FOUND AND NOT TARGET ROSCO::ROSCO)
  add_library(ROSCO::ROSCO UNKNOWN IMPORTED)
  set_target_properties(ROSCO::ROSCO PROPERTIES
    IMPORTED_LOCATION "${ROSCO_LIBRARY}"
    IMPORTED_LINK_INTERFACE_LIBRARIES "${CMAKE_DL_LIBS}"
    INTERFACE_COMPILE_OPTIONS "${PC_ROSCO_CFLAGS_OTHER}"
    #INTERFACE_INCLUDE_DIRECTORIES "${ROSCO_INCLUDE_DIR}"
  )
endif()

mark_as_advanced(
  #ROSCO_INCLUDE_DIR
  ROSCO_LIBRARY
)

# compatibility variables
set(ROSCO_VERSION_STRING ${ROSCO_VERSION})
