find_package(PkgConfig)
pkg_check_modules(PC_INFLOWWIND QUIET INFLOWWIND)

find_library(INFLOWWIND_LIBRARY
  NAMES libifw_c_binding.so
  PATHS ${PC_INFLOWWIND_LIBRARY_DIRS}
)

set(PC_INFLOWWIND_VERSION "0.1.0")

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(INFLOWWIND
  FOUND_VAR INFLOWWIND_FOUND
  REQUIRED_VARS INFLOWWIND_LIBRARY
  VERSION_VAR INFLOWWIND_VERSION
)

if(INFLOWWIND_FOUND)
  set(INFLOWWIND_LIBRARIES ${INFLOWWIND_LIBRARY} ${CMAKE_DL_LIBS})
  set(INFLOWWIND_DEFINITIONS ${PC_INFLOWWIND_CFLAGS_OTHER})
endif()

if(INFLOWWIND_FOUND AND NOT TARGET INFLOWWIND::INFLOWWIND)
  add_library(INFLOWWIND::INFLOWWIND UNKNOWN IMPORTED)
  set_target_properties(INFLOWWIND::INFLOWWIND PROPERTIES
    IMPORTED_LOCATION "${INFLOWWIND_LIBRARY}"
    IMPORTED_LINK_INTERFACE_LIBRARIES "${CMAKE_DL_LIBS}"
    INTERFACE_COMPILE_OPTIONS "${PC_INFLOWWIND_CFLAGS_OTHER}"
  )
endif()

mark_as_advanced(
  INFLOWWIND_LIBRARY
)

# compatibility variables
set(INFLOWWIND_VERSION_STRING ${INFLOWWIND_VERSION})
