find_package(PkgConfig)
pkg_check_modules(PC_AERODYN QUIET AERODYN)

find_library(AERODYN_LIBRARY
  NAMES aerodyn
  PATHS ${PC_AERODYN_LIBRARY_DIRS}
)

set(PC_AERODYN_VERSION "1.0.0") #${PC_AERODYN_VERSION})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(AERODYN
  FOUND_VAR AERODYN_FOUND
  REQUIRED_VARS
    AERODYN_LIBRARY
    #AERODYN_INCLUDE_DIR
  VERSION_VAR AERODYN_VERSION
)

if(AERODYN_FOUND)
  set(AERODYN_LIBRARIES ${AERODYN_LIBRARY} ${CMAKE_DL_LIBS})
  #set(AERODYN_INCLUDE_DIRS ${AERODYN_INCLUDE_DIR})
  set(AERODYN_DEFINITIONS ${PC_AERODYN_CFLAGS_OTHER})
endif()

if(AERODYN_FOUND AND NOT TARGET AERODYN::AERODYN)
  add_library(AERODYN::AERODYN UNKNOWN IMPORTED)
  set_target_properties(AERODYN::AERODYN PROPERTIES
    IMPORTED_LOCATION "${AERODYN_LIBRARY}"
    IMPORTED_LINK_INTERFACE_LIBRARIES "${CMAKE_DL_LIBS}"
    INTERFACE_COMPILE_OPTIONS "${PC_AERODYN_CFLAGS_OTHER}"
    #INTERFACE_INCLUDE_DIRECTORIES "${AERODYN_INCLUDE_DIR}"
  )
endif()

mark_as_advanced(
  #AERODYN_INCLUDE_DIR
  AERODYN_LIBRARY
)

# compatibility variables
set(AERODYN_VERSION_STRING ${AERODYN_VERSION})
